### ISSUE TITLE
missing bib entries in literaturelist.bib

### ISSUE THREAD

**Issue by kstolee** [Felienne/end_user_refactoring#11]
Warning--I didn't find a database entry for "Wins2001"
Warning--I didn't find a database entry for "Pank2006"

**Comment by Felienne** [comment]
Ow, I did not push the changes to the bib file I think. Will fix.

**Comment by Felienne** [comment]
Should work now, fixed by https://github.com/Felienne/end_user_refactoring/commit/a97eef970629b919631d45c903094cd9a8c98f51
