### ISSUE TITLE
Message from Chris Scaffidi

### ISSUE THREAD

**Issue by kstolee** [Felienne/end_user_refactoring#4]
Here's a response from Chris re: refactoring in LabVIEW. They have some work accepted for publicaiton on the topic (pdf in repo now). We need to read and integrate:

We did implement automatic fixing of smells in LabVIEW. You can read all about it in Chris Chamber's dissertation... the relevant portion that you're talking about is going to appear in the paper cited below (see attached for the text of what I expect to be published). 

Chambers, C., and Scaffidi, C. (2015). Impact and utility of smell-driven performance tuning for end-user programmers. Journal of Visual Languages and Computing, to appear.

An important thing to note in our paper is that refactoring is nice, but semantics-non-preserving transformations are often necessary to get the best improvement in performance when removing smells.

I don't plan to follow up on these transformations now that Chris is graduated. We only implemented them for LabVIEW, so there's a lot of work left to be done for other languages...

**Comment by dhoepelman** [comment]
That's good to know, I'll take a look at it today.

**Comment by dhoepelman** [comment]
As expected they mainly deal with changes to improve performance, and not all are refactorings in the strict sense of the word. They also don't map very well to OO, Excel or Pipe refactorings. I'll see what I can write in the domain-specific section.
