### ISSUE TITLE
"Spreadsheets" or "Excel"

### ISSUE THREAD

**Issue by dhoepelman** [Felienne/end_user_refactoring#5]
Kathy changed "spreadsheets" to Excel everywhere, probably to be more uniform because we used LabVIEW and Yahoo Pipes in most places. But our work is applicable to all current spreadsheet software and not just to Excel. (e.g. OpenOffice/LibreOffice calc, Google Docs, Office 365 online).

Pipe-like mashups and G are very tightly bound to their implementation (Yahoo Pipes and LabVIEW), and I don't think that alternative implementations exists. As such I think the implementation name is appropriate there.

Which do we want to use?

**Comment by Felienne** [comment]
Yeah, I can see why that is more consistent for this paper. Let's do add a note somewhere (in the discussion) explaining that in principle out work is more general.
